name: movie_viewer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  provider: ^6.1.1
  window_manager: ^0.3.7
  html: ^0.15.4
  http: ^1.1.0
  dynamic_color: ^1.6.8
  shared_preferences: ^2.2.1
  transparent_image: ^2.0.0
  youtube_explode_dart: ^2.0.2
  flutter_hls_parser: ^2.0.1
  win32: ^5.1.0
  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master

dependency_overrides:
  audio_video_progress_bar: ^2.0.1
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      ref: master
      path: ffi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
